name: Flutter

on:
  push: 
    tags:
      - v*

permissions:
  contents: write

jobs:
  get_tag:

    runs-on: ubuntu-latest

    steps:

      # Clones the project on the machine
      - uses: actions/checkout@v4
      
      # Get Tag Name
      - name: Get tag name
        id: get_tag_name
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

  release:

    # This job will only run if the get_tag job is successful
    needs: get_tag
    runs-on: ubuntu-latest

    steps:
      
      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Cleanup Build Artefacts
      - name: Clean up build artifacts
        run: |
          set -e

          sha=`sha256sum release.apk.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          sha=`sha256sum release-arm64-v8a.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          sha=`sha256sum release-armeabi-v7a.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
          
          sha=`sha256sum release-x86_64.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      # Creates a GitHub release and uploads the APK
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: My Wallpapers ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
            
            ## If you are unsure which version to choose then go with my-wallpapers-${{ env.VERSION_TAG }}.apk
          files: |
            my-wallpapers-${{ env.VERSION_TAG }}.apk
            my-wallpapers-arm64-v8a-${{ env.VERSION_TAG }}.apk
            my-wallpapers-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            my-wallpapers-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        