name: Release-v1

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      
      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Get Tag Name
      - name: Get tag name
        id: get_tag_name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      
      # Setup NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"
      
      # Npm Install
      - name: NPM install
        run: npm i

      # Build Apps
      - name: Merge Chunks
        run: node index.js

      # Build Apps
      - name: Build Apps
        run: node index2.js

      # Cleanup Build Artefacts
      - name: Calculate SHA/Checksum
        run: |
          set -e

          sha=`sha256sum output/release.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL=$sha" >> $GITHUB_ENV

          sha=`sha256sum output/release-arm64-v8a.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          sha=`sha256sum output/release-armeabi-v7a.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV
          
          sha=`sha256sum output/release-x86_64.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      # Append version name to Apps
      - name: Append version to filename
        run: |
          set -e

          mv output/release.apk output/release-universal-v${{ env.VERSION_TAG }}.apk

          mv output/release-arm64-v8a.apk output/release-arm64-v8a-v${{ env.VERSION_TAG }}.apk

          mv output/release-armeabi-v7a.apk output/release-armeabi-v7a-v${{ env.VERSION_TAG }}.apk
          
          mv output/release-x86_64.apk output/release-x86_64-v${{ env.VERSION_TAG }}.apk

      # Creates a GitHub release and uploads the APK
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          fail_on_unmatched_files: true
          name: My Wallpapers ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | universal | ${{ env.APK_UNIVERSAL }} |
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }} |
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }} |
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
            
            ## If you are unsure which version to choose then go with release-universal-v${{ env.VERSION_TAG }}.apk
          files: |
            output/release-universal-v${{ env.VERSION_TAG }}.apk
            output/release-arm64-v8a-v${{ env.VERSION_TAG }}.apk
            output/release-x86_64-v${{ env.VERSION_TAG }}.apk
            output/release-universal-v${{ env.VERSION_TAG }}.apk

          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}